# Generated by Django 4.2.30 on 2026-08-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_customer_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labvaultglobalprefs',
            name='ui_column_profiles',
            field=models.JSONField(blank=True, default=dict, help_text='Map of surface id → column profile store (shared org-wide)'),
        ),
    ]
